name: islami
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  gap: ^3.0.1
  intl: ^0.19.0
  date_picker_timeline: ^1.2.6
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  carousel_slider: ^5.0.0
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  geolocator: ^13.0.2
  geocoding: 3.0.0
  adhan: ^2.0.0+1
  hijri: ^3.0.0
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  animated_custom_dropdown: ^3.1.1
  provider: ^6.1.2
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.8.0
  quran: ^1.3.1
  audioplayers: ^6.1.0
  just_audio: ^0.9.42
  flutter_compass: ^0.8.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/azkar/
    - assets/images/bg/
    - assets/images/onboard/
    - assets/images/seb7a/
    - assets/icons/
    - assets/json/adhkar.json
 
  # fonts:
  fonts:
  - family: AppFonts.fontFamily
    fonts:
      - asset: assets/fonts/ArbFONTS-Janna-LT-Regular.ttf
      - asset: assets/fonts/Janna LT Bold.ttf

